## 9장 확인 문제 풀이

### 1. 중첩 멤버 클래스

- 인스턴스 멤버 클래스는 바깥 클래스의 객체가 있어야 사용 가능
  - 바깥 클래스가 생성되어 있으니 그 필드와 메소드를 사용할 수 있음
- 정적 멤버 클래스는 바깥 클래스 생성 없이 사용 가능
  - 만들어지지 않은 인스턴스 필드는 사용할 수 없음

### 2. 로컬 클래스

- 메소드 내부에 선언된 클래스
- 바깥 클래스 객체가 생성된 후에 사용할 수 있으므로 바깥 클래스의 모든 필드와 메소드 사용 가능
- static 키워드를 이용해서 정적 클래스로 만들 수 없음
  - 메소드는 호출되었다가 끝나면 사라지므로 안에서 static을 쓰지 않음
- **final 특성을 가진 매개 변수나 로컬 변수만 로컬 클래스 내부에서 사용할 수 있음**

### 3. 익명 객체

- 클래스를 상속하거나 인터페이스를 구현해야만 생성될 수 있음
- 필드, 매개 변수, 로컬 변수의 초기값으로 주로 사용됨
- 생성자 선언 불가
  - 부모의 생성자 호출
- 부모 클래스나 인터페이스에 선언된 필드와 메소드 이외의 다른 필드와 메소드를 선언할 수 있지만 익명 객체 내부에서만 사용 가능

### 6. 컴파일 에러 원인

```java
String nickName = null;
nickName = chatId;
Chat chat = new Chat() {
    @Override
    public void start() {
        ...
        String message = ... + nickname + ...;
        ...
    }
}
```

- Chat 클래스의 자식을 부모 타입에 upcasting한 것

- 익명 객체를 생성하는 과정에서 nickName을 사용함

  - nickName은 final로 선언되지 않은 지역 변수이므로 사용할 수 없음

- 선언과 함께 초기화 하면 자동으로 final로 선언됨

  ```java
  String nickName = chatId; // final
  ```

  - 자바 낮은 버전에서는 지원하지 않는 경우도 있으니 final을 쓰는 게 좋음



# 10. 예외 처리

```java
public class ExceptionSample1 {

	public static void main(String[] args) {
		String str = "hi";
		int a=10, b=0;
		try {
			System.out.println(str.toString());
			System.out.println(a/b);
		} catch (NullPointerException e) {
			// 예외 상황이 발생했을 때 처리할 사항
			System.out.println(e.getMessage());
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		
		System.out.println("프로그램 종료");
	}
}
```

- `try` ~ `catch`를 이용하여 예외 처리
- 예외 처리도 순서대로 하므로 Exception(모든 예외 상황)은 제일 나중에 처리
- `getMessage()` : 에러 메시지



- try의 위치에 따라 달라짐

  - 한번 예외 발생하면 반복문 종료

    ```java
    public class ExceptionSample2 {
    
    	public static void main(String[] args) {
    		int[] arr1 = {10,20,30,40};
    		int[] arr2 = {2,0,6};
    
    		try {
    			for (int i = 0; i < arr1.length; i++) {
    					System.out.println(arr1[i] / arr2[i]);
    			}
    		} catch (ArithmeticException e) {
    			System.out.println(e.getMessage());
    		} catch (ArrayIndexOutOfBoundsException e) {
    			System.out.println(e.getMessage());
    		}
    	}
    }
    
    // 출력
    // 5
    // / by zero
    ```

  - 하나하나씩 예외처리하므로 예외가 발생해도 다음 반복문 실행

    ```java
    public class ExceptionSample2 {
    
    	public static void main(String[] args) {
    		int[] arr1 = {10,20,30,40 };
    		int[] arr2 = {2,0,4};
    
    		for (int i = 0; i < arr1.length; i++) {
    			try {
    				System.out.println(arr1[i] / arr2[i]);
    			} catch (ArithmeticException e) {
    				System.out.println(e.getMessage());
    			} catch (ArrayIndexOutOfBoundsException e) {
    				System.out.println(e.getMessage());
    			}
    		}
    	}
    }
    
    // 출력
    // 5
    // by zero
    // 5
    // Index 3 out of bounds for length 3
    ```



## try-catch-finally

- finally : 예외가 발생하든 안 하든 항상 실행
  - 중간에 예외가 발생하거나 return 등으로 try문이 종료되더라도 실행됨



## throw

- 예외를 직접 만들어서 던질 수 있음

  ```java
  public class ExceptionSample6 {
  
  	public static void main(String[] args) {
  		try {
  			throw new Exception("내가 만든 예외");
  		} catch (Exception e) {
  			System.out.println(e.getMessage());
  		}
  	}
  }
  ```

- 원래는 던져야 하는데(throw), 원래 있는 함수에서는 예외 던지는 것까지 포함되어 있어서 아까 따로 throw하지 않아도 예외 처리가 된 것

- 함수 내에서 던져지는 예외가 있다면 함수 정의할 때`throws` 써야 함

  ```java
  public class ExceptionSample7 {
  	public static void method1() throws Exception {
  		method2();
  	}
  	public static void method2() throws Exception {
  		String str = null;
  		try {
  			System.out.println(str.toString());
  		} catch (NullPointerException e) {
  			System.out.println(e.getMessage());
  			throw new Exception("다시 생성한 예외");
  		}
  	}
  	public static void main(String[] args) {
  		try {
  			method1();
  		} catch (Exception e) {
  			System.out.println(e.getMessage());
  		}
  	}
  }
  ```



## 사용자 정의 예외와 예외 발생

- 선언 방법

  ```java
  public class XXXException extends [Exception | RuntimeException ] {
      public XXXException() {}
      public XXXException(String message) {
          super(message);
      }
  }
  ```

- 예외 발생 시키기

  ```java
  throw new XXXException();
  throw new XXXException("메시지");
  ```



# 12. 멀티 스레드

## 프로세스(process)

> 실행 중인 하나의 프로그램



## 멀티 태스킹

> 두가지 이상의 작업을 동시에 처리하는 것

- 멀티 프로세스 : 독립적으로 프로그램들을 실행하고 여러 가지 작업 처리
- 멀티 스레드 : 한 개의 프로그램을 실행하고 내부적으로 여러 가지 작업 처리
  - 메인은 하나의 스레드! 우리는 여태까지 싱글 스레드로 작업하고 있었음

- Thread.currentThread() : 현재 실행 되고 있는 스레드
- Thread.currentThread().getName() : 현재 실행되고 있는 스레드의 이름

- 스레드 이름은 Thread-`N` (기본값)

  ```java
  Thread thread1 = new Thread();
  System.out.println(thread1.getName()); // Thread-0
  ```

  - 이름 정해줄 수 있음

    ```java
    Thread thread1 = new Thread("ThreadA");
    System.out.println(thread1.getName()); // ThreadA
    ```



## 스레드 우선 순위

- 동시성 : 멀티 작업을 위해 **하나의 코어**에서 **멀티 스레드**가 번갈아가며 실행하는 성질
- 병렬성 : 멀티 작업을 위해 **멀티 코어**에서 **개별 스레드**를 동시에 실행하는 성질



### 스레드 스케줄링

- 스레드의 개수가 코어의 수보다 많을 경우
  - 스레드를 어떤 순서로 동시성으로 실행할 것인가 결정
  - 스케줄링에 의해 스레드들은 번갈아가며 run() 메소드를 조금씩 실행
- 자바의 스레드 스케줄링 : 우선 순위 방식과 순환 할당 방식 사용

#### 우선 순위 (Priority) 방식

- 코드로 제어 가능
- 우선 순위가 높은 스레드가 실행 상태를 더 많이 가지도록 스케줄링
- 1~10의 값을 가지며, 기본은 5

#### 순환 할당 (Round-Robin) 방식

- 코드로 제어 불가능
- 시간 할당량(Time Slice)을 정해서 하나의 스레드를 정해진 시간만큼 실행



## 동기화 메소드와 동기화 블록

> 단 하나의 스레드만 실행할 수 있는 스레드나 블록

- `synchronized` : 하나의 스레드가 호출하면 다른 스레드는 이미 실행되고 있는 스레드가 끝날 때까지 대기함

- 동기화 메소드

  ```java
  public synchronized void method() {
      ... // 단 하나의 스레드만 실행
  }
  ```

- 동기화 블록

  ```java
  public void method() {
      ... // 여러 스레드가 실행 가능
      synchronized(공유객체) { // 공유 객체가 객체 자신이면 this를 넣을 수 있음
          ... // 단 하나의 스레드만 실행
      }
      ... // 여러 스레드가 실행 가능
  }
  ```



## 스레드 상태

- 스레드의 일반적인 상태
  - 스레드 객체 생성 -> `실행 대기 <-> 실행 (반복)` -> 종료



## 스레드 상태 제어

> 실행 중인 스레드의 상태를 변경하는 것

